export const items = [
  {
    id: 1,
    category: "mobile",
    title: "Apple iphone 14",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Apple iphone 14 (64 GB) - Blue",
    price: "19999",
  },
  {
    id: 5,
    category: "laptop",
    title: "Dell laptop",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Dell core-i5",
    price: "52999",
  },
  {
    id: 7,
    category: "laptop",
    title: "Dell laptop",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Dell core-i3",
    price: "39999",
  },
  {
    id: 2,
    category: "mobile",
    title: "Apple iphone 14 max",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonlink: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    description: "Apple iphone 14 (128 GB) - white",
    price: "49999",
  },
  {
    id: 6,
    category: "laptop",
    title: "Dell laptop",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Dell core-i7",
    price: "99999",
  },
  {
    id: 3,
    category: "mobile",
    title: "Apple iphone 14 pro max",
    imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Apple iphone 14 (256 GB) - Black",
    price: "70999",
  },
  {
    id: 4,
    category: "tablet",
    title: "Samsung Galaxy Tablet",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Samsung Talet",
    price: "91999",
  },
  {
    id: 9,
    category: "tablet",
    title: "Samsung Galaxy Tablet",
    imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Samsung Talet 3",
    price: "71999",
  },
 
  {
    id: 8,
    category: "tablet",
    title: "Samsung Galaxy Tablet",
    imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
    amazonlink: "https://unsplash.com/s/photos/iphone-14-pro",
    description: "Samsung Talet",
    price: "50999",
  },
  


];
